### PR TITLE
Add fade functionality with flickity-fade

### PR DESCRIPTION
**Pull request by JodiWarren**
I've basically just replaced `flickity` with `flickity-fade`. It's almost identical in size and allows for fade transitions.

### CODE REVIEW

**Comment by yaodingyd** [comment]
Thanks for your contribution! 

However I don't think this is necessary and the right direction to go. To use fade you can just import flickity-fade package and specify that option. check example here:https://codesandbox.io/s/react-flickity-difcr

**Comment by frazerf** [comment]
Hi @yaodingyd I've implemented fade the same way you have above but I'm getting a lint error, as you are in your example, of import fade from "flickity-fade";

Is there anyway for this to be fixed?

**Comment by yaodingyd** [comment]
@frazerf just disable lint for this line

**Comment by alexkerber** [comment]
can this PR be fixed with the conflicts and merged? :)

**Comment by joshiefishbein** [comment]
Just to have this answered for people in the meantime, I followed @yaodingyd's advice when using `react-flickity-component` to get fade from `flickity-fade` working with typescript:

```typescript
import Flickity from 'react-flickity-component';
import 'flickity-fade';

const Carousel = () => (
  <Flickity
    options={{
      // @ts-ignore
      fade: true
    }}
  >
    {/* slides... */}
  </Flickity>
);
```

**Pull request closed without merging**
