### PR TITLE
Add declaration file for typescript types

### PR DESCRIPTION
**Pull request by justinemmanuelmercado**
https://github.com/theolampert/react-flickity-component/issues/52

### CODE REVIEW

**Comment by justinemmanuelmercado** [comment]
No problem, thank you for your work! 👍

**Comment by justinemmanuelmercado** [comment]
Hey @theolampert, maybe we could hold off on releasing this for now, I think I should submit a PR to DefinitelyTyped first just to get the FlickityOptions interface exported instead of hard coding the interface here. I'll update this when my PR there gets merged.

**Comment by theolampert** [comment]
@justinemmanuelmercado sounds good, no rush on releasing.

**Comment by timdev** [comment]
Chiming in here, as I work with @justinemmanuelmercado.

The issue we ran into in our discussion is that if we submit a PR to DefinitelyTyped to expose FlickityOptions (instead of duplicating the interface here, as this PR does currently), we'll need to add a dependency on `@types/flickity` to this project.  

I'm not expecting any strong objection, but wanted to ping @theolampert for thoughts before we proceed.

**Comment by theolampert** [comment]
@timdev Hey!, I'm not against adding the typings as a dependency, particularly if it means less maintenance for this package going forward, simply bumping the typings when I pump the flickity dependency would make it easier for me.

**Pull request merged**
