### PR TITLE
Updated declare class with relevant functions in typescript types declaration

### PR DESCRIPTION
**Pull request by shabith**

### CODE REVIEW

**Comment by shabith** [comment]
I have added the most of the missing functions to the typescript definition file.

**Comment by theolampert** [comment]
@shabith thank you very much for your work here.

> I have added the most of the missing functions to the typescript definition file.

Does this mean there are still some functions missing?

**Comment by shabith** [comment]
> Does this mean there are still some functions missing?

Hi @theolampert, I didn't add the fullscreen related functions as it is related to another plugin. However after checking it again, I feel there is no harm adding that as well :) Shall I add those and resubmit a PR?

**Comment by theolampert** [comment]
@shabith yes that would probably be the easiest for the end user, I can add a note about plugins to the readme. Thanks!

**Comment by shabith** [comment]
Hi @theolampert I have added the missing fullScreen plugin related functions.

**Comment by theolampert** [comment]
@shabith thanks alot this seems to work well for me. I have to head off but I'll merge this now and release a bit later on.

**Pull request merged**
